<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trading.Core\Trading.Core.csproj" />
    <ProjectReference Include="..\Trading.EventBus.RabbitMQ\Trading.EventBus.RabbitMQ.csproj" />
    <ProjectReference Include="..\Trading.Processors\Trading.Processors.csproj" />
    <ProjectReference Include="..\Trading.Storage\Trading.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
