<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Trading.Core">
	    <HintPath>..\..\..\TradingPlatform05\Trading.Core\bin\Debug\net10.0\Trading.Core.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
